### ISSUE TITLE
use octo-sts for read access to policy library

### ISSUE THREAD

**Issue by amber-beasley-liatrio** [liatrio/.github#7]
# Summary

As an engineer,

I want to use the octo-sts action to create a read contents read token for the policy library bundle during the opa evaluation job,

so that I can get rid of the PAT token needed to download it.

# To Do

- [ ] add a new trust policy file `policy-library.sts.yaml` to the .github repo https://github.com/liatrio/.github
  - add permissions: `contents: read`
  - add repositories (we want to let any Liatrio repo read contents so you will need to test around to see if we can use a * or regular expression to allow all Liatrio repos)
- [ ] add token creation octo-sts step to the opa eval jobs and replace the PAT token reference with the new octo-sts output reference

```yaml
steps:
      - uses: actions/checkout@v4

      - name: Generate a token
        id: generate_token
        uses: octo-sts/action@6177b4481c00308b3839969c3eca88c96a91775f # v1.0.0
        with:
          scope: liatrio
          identity: policy-library # liatrio/.github/chainguard/policy-library.sts.yaml

      - name: Do something with the token
        run: |
          <do something with the token> --token ${{ steps.generate_token.outputs.token }}
```
